# Generated by Django 3.1.6 on 2021-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_likebutton_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likebutton',
            name='likes',
        ),
        migrations.AddField(
            model_name='likebutton',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
